app:
  name: "spring-auth-apis"
  login:
    username: "root"
    password: "admin"
  JWT:
    secret: "mySecretKeyForJWTTokenGenerationAndValidation123456789"
    expiration: 36000
  products:
    - id: 1
      name: "Product A"
      price: 19.99
    - id: 2
      name: "Product B"
      price: 29.99
    - id: 3
      name: "Product C"
      price: 39.99
    - id: 4
      name: "Product D"
      price: 49.99